version: '3.3'

volumes:
  questionbot_postgres_data: { }
  questionbot_postgres_data_backups: { }
  questionbot_redis_data:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile

    image: questionbot_local_django
    container_name: questionbot_local_django
    hostname: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=api.core.local
    command: /start
    networks:
      - tg_bot


  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
      - .:/usr/src/app/${BOT_NAME:-tg_bot}
    depends_on:
      - django
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: questionbot_postgres_image
    container_name: questionbot_local_postgres
    volumes:
      - questionbot_postgres_data:/var/lib/postgresql/data
      - questionbot_postgres_data_backups:/backups
    env_file:
      - .env
    networks:
      - tg_bot

  redis:
    image: redis
    ports:
      - "6380:6380"
    volumes:
      - questionbot_redis_data:/data
    command: redis-server --port 6380 --appendonly yes
    networks:
      - tg_bot

networks:
  tg_bot:
    driver: bridge